INSERT INTO Course(courseId) VALUES(1,'Biology',1,1,2,);
INSERT INTO Course(courseId) VALUES(2,'AP Biology',2,3,2,);
INSERT INTO Course(courseId) VALUES(3,'AP Biology Lab',3,3,2,);
INSERT INTO Course(courseId) VALUES(4,'Physics',5,1,2,);
INSERT INTO Course(courseId) VALUES(5,'Precalculus',3,1,1,);
INSERT INTO Course(courseId) VALUES(6,'Geometry',8,1,1,);
INSERT INTO Course(courseId) VALUES(7,'AB Calculus',4,3,1,);
INSERT INTO Course(courseId) VALUES(8,'AP US History',5,3,3,);
INSERT INTO Course(courseId) VALUES(9,'Government',9,1,3,);
INSERT INTO Course(courseId) VALUES(10,'US History',6,1,3,);
INSERT INTO Course(courseId) VALUES(11,'Into to Lit',1,1,4,);
INSERT INTO Course(courseId) VALUES(12,'American Lit',5,1,4,);
INSERT INTO Course(courseId) VALUES(13,'Brit Lit',1,1,4,);
INSERT INTO Course(courseId) VALUES(14,'AP Lit',4,3,4,);
INSERT INTO Course(courseId) VALUES(15,'Span II',3,2,5,);
INSERT INTO Course(courseId) VALUES(16,'Span III',9,2,5,);
INSERT INTO Course(courseId) VALUES(17,'Span IV',7,2,5,);
INSERT INTO Course(courseId) VALUES(18,'AP Span',5,3,5,);
INSERT INTO Course(courseId) VALUES(19,'Adv CT',4,2,6,);
INSERT INTO Course(courseId) VALUES(20,'Adv CS',4,2,6,);
INSERT INTO Course(courseId) VALUES(21,'OOP Java',1,3,6,);
INSERT INTO Course(courseId) VALUES(22,'Band',5,1,7,);
INSERT INTO Course(courseId) VALUES(23,'Music Tech',2,1,7,);
INSERT INTO Course(courseId) VALUES(24,'Choir',3,1,7,);
INSERT INTO Course(courseId) VALUES(25,'Chamber Singers',4,1,7,);
INSERT INTO Course(courseId) VALUES(26,'Orchestra',5,1,7,);
INSERT INTO Course(courseId) VALUES(27,'Theatre',5,1,7,);
INSERT INTO Course(courseId) VALUES(28,'Photography',5,1,7,);
INSERT INTO Course(courseId) VALUES(29,'Photography',6,1,7,);
INSERT INTO Course(courseId) VALUES(30,'Visual Arts',7,1,7,);
INSERT INTO Course(courseId) VALUES(31,'Visual Arts',8,1,7,);
INSERT INTO Course(courseId) VALUES(32,'Visual Arts',9,1,7,);
